services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: artoriax
      POSTGRES_PASSWORD: Himanshu@864
      POSTGRES_DB: mydb
    ports:
      - '5432:5432' # Map container port to host port
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
